---
kind: pipeline
type: docker
name: default

steps:
- name: build-docker
  image: plugins/docker
  settings:
    registry: registry.shitangdama.cn
    repo: registry.shitangdama.cn/dama/viki-app
    dockerfile: Dockerfile
    username: shitangdama
    password:
      from_secret: docker_password
    tag:
      - latest
  when:
    branch:
      - master